name: Scala CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
      - uses: actions/setup-java@v1
      with:
        java-version: '8'
      - uses: actions/checkout@v2
      - name: Run tests
        run: mvn test
