name: Scala CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setupEnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: mvn test
