name: Scala CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setupEnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: mvn test
